// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buptfxlfwtnpkqojmbuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1cHRmeGxmd3RucGtxb2ptYnVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTExMDksImV4cCI6MjA2NjE4NzEwOX0.DF-I01wXINGV8RoRQjQpcsYrm1u7QPPedr5BRvzTINk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});